spring:
  #datasource:
    #url: jdbc:mysql://192.168.147.128:3306/webdemo?useUnicode=true&characterEncoding=utf8
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #password: 123456
  application:
    name: webdemo-order

server:
  port: 8010
eureka:
  #instance:
  #hostname: 127.0.0.1
  #lease-renewal-interval-in-seconds: 1
  #lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
      #,http://localhost:8200/eureka
    register-with-eureka: true
    fetch-registry: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000