server:
  port: 8002
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka,http://localhost:8100/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: webdemo-user