server:
  port: 8100
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
    #eureka集群
      #defaultZone: http://${eureka.instance.hostname}:8200/eureka/
    #register-with-eureka: true
    #fetch-registry: true
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
spring:
  application:
    name: webdemo-eureka