spring:
  application:
    name: config-client
  cloud:
    config:
      profile: dev
      discovery:
        service-id: config-server
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
server:
  port: 8889